/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cafelinear_ndkdemo_PrintLib */

#ifndef _Included_com_cafelinear_ndkdemo_PrintLib
#define _Included_com_cafelinear_ndkdemo_PrintLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cafelinear_ndkdemo_PrintLib
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cafelinear_ndkdemo_PrintLib_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
